const BASE_URL = "https://api.unsplash.com/";
const END_POINT = "/search/photos"; //https://unsplash.com/documentation#schema
const client_id = "yIp7KhzFsb4CVLb9gfY9k_AaLKTzD1SqXwegwczqCVs";
export const URL = `${BASE_URL}${END_POINT}?client_id=${client_id}`;
// export const URL = "https://jsonplaceholder.typicode.com/photos";

export const arrPhotos = [
  {
    id: "dIfsOkzzSk4",
    slug: "a-man-holding-a-cell-phone-in-his-hand-dIfsOkzzSk4",
    alternative_slugs: {
      en: "a-man-holding-a-cell-phone-in-his-hand-dIfsOkzzSk4",
      es: "un-hombre-con-un-telefono-celular-en-la-mano-dIfsOkzzSk4",
      ja: "携帯電話を手にした男性-dIfsOkzzSk4",
      fr: "un-homme-tenant-un-telephone-portable-a-la-main-dIfsOkzzSk4",
      it: "un-uomo-che-tiene-in-mano-un-telefono-cellulare-dIfsOkzzSk4",
      ko: "핸드폰을-손에-들고-있는-남자-dIfsOkzzSk4",
      de: "ein-mann-mit-einem-handy-in-der-hand-dIfsOkzzSk4",
      pt: "um-homem-com-um-celular-na-mao-dIfsOkzzSk4",
    },
    created_at: "2024-07-02T16:19:28Z",
    updated_at: "2024-07-19T18:09:14Z",
    promoted_at: null,
    width: 3600,
    height: 2396,
    color: "#73a6c0",
    blur_hash: "LJCa3*McQRAcTyVXMxtlT0t7MxeS",
    description: null,
    alt_description: "A man holding a cell phone in his hand",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1719937051157-d3d81cc28e86?ixid=M3w2MzUxOTV8MXwxfGFsbHwxfHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1719937051157-d3d81cc28e86?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MzUxOTV8MXwxfGFsbHwxfHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1719937051157-d3d81cc28e86?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzUxOTV8MXwxfGFsbHwxfHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1719937051157-d3d81cc28e86?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzUxOTV8MXwxfGFsbHwxfHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1719937051157-d3d81cc28e86?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzUxOTV8MXwxfGFsbHwxfHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1719937051157-d3d81cc28e86",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-man-holding-a-cell-phone-in-his-hand-dIfsOkzzSk4",
      html: "https://unsplash.com/photos/a-man-holding-a-cell-phone-in-his-hand-dIfsOkzzSk4",
      download:
        "https://unsplash.com/photos/dIfsOkzzSk4/download?ixid=M3w2MzUxOTV8MXwxfGFsbHwxfHx8fHx8Mnx8MTcyMTU1NjY5MXw",
      download_location:
        "https://api.unsplash.com/photos/dIfsOkzzSk4/download?ixid=M3w2MzUxOTV8MXwxfGFsbHwxfHx8fHx8Mnx8MTcyMTU1NjY5MXw",
    },
    likes: 4,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: {
      impression_urls: [
        "https://secure.insightexpressai.com/adServer/adServerESI.aspx?script=false&bannerID=12236422&rnd=[timestamp]&redir=https://secure.insightexpressai.com/adserver/1pixel.gif",
      ],
      tagline: "Memory for every endeavor",
      tagline_url: "https://www.samsung.com/us/memory-storage/",
      sponsor: {
        id: "eySMK9KwmJU",
        updated_at: "2024-07-21T08:46:11Z",
        username: "samsungmemory",
        name: "Samsung Memory",
        first_name: "Samsung",
        last_name: "Memory",
        twitter_username: "SamsungSemiUS",
        portfolio_url: "http://www.samsung.com/us/computing/memory-storage/",
        bio: "Memory for every endeavor – get fast storage solutions that work seamlessly with your devices.",
        location: null,
        links: {
          self: "https://api.unsplash.com/users/samsungmemory",
          html: "https://unsplash.com/@samsungmemory",
          photos: "https://api.unsplash.com/users/samsungmemory/photos",
          likes: "https://api.unsplash.com/users/samsungmemory/likes",
          portfolio: "https://api.unsplash.com/users/samsungmemory/portfolio",
          following: "https://api.unsplash.com/users/samsungmemory/following",
          followers: "https://api.unsplash.com/users/samsungmemory/followers",
        },
        profile_image: {
          small:
            "https://images.unsplash.com/profile-1602741027167-c4d707fcfc85image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
          medium:
            "https://images.unsplash.com/profile-1602741027167-c4d707fcfc85image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
          large:
            "https://images.unsplash.com/profile-1602741027167-c4d707fcfc85image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
        },
        instagram_username: "samsungsemiconductor",
        total_collections: 1,
        total_likes: 0,
        total_photos: 880,
        total_promoted_photos: 38,
        total_illustrations: 0,
        total_promoted_illustrations: 0,
        accepted_tos: true,
        for_hire: false,
        social: {
          instagram_username: "samsungsemiconductor",
          portfolio_url: "http://www.samsung.com/us/computing/memory-storage/",
          twitter_username: "SamsungSemiUS",
          paypal_email: null,
        },
      },
    },
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "eySMK9KwmJU",
      updated_at: "2024-07-21T08:46:11Z",
      username: "samsungmemory",
      name: "Samsung Memory",
      first_name: "Samsung",
      last_name: "Memory",
      twitter_username: "SamsungSemiUS",
      portfolio_url: "http://www.samsung.com/us/computing/memory-storage/",
      bio: "Memory for every endeavor – get fast storage solutions that work seamlessly with your devices.",
      location: null,
      links: {
        self: "https://api.unsplash.com/users/samsungmemory",
        html: "https://unsplash.com/@samsungmemory",
        photos: "https://api.unsplash.com/users/samsungmemory/photos",
        likes: "https://api.unsplash.com/users/samsungmemory/likes",
        portfolio: "https://api.unsplash.com/users/samsungmemory/portfolio",
        following: "https://api.unsplash.com/users/samsungmemory/following",
        followers: "https://api.unsplash.com/users/samsungmemory/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1602741027167-c4d707fcfc85image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1602741027167-c4d707fcfc85image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1602741027167-c4d707fcfc85image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "samsungsemiconductor",
      total_collections: 1,
      total_likes: 0,
      total_photos: 880,
      total_promoted_photos: 38,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: "samsungsemiconductor",
        portfolio_url: "http://www.samsung.com/us/computing/memory-storage/",
        twitter_username: "SamsungSemiUS",
        paypal_email: null,
      },
    },
  },
  {
    id: "TQ5unA1BWDw",
    slug: "a-close-up-of-a-blue-object-on-a-white-surface-TQ5unA1BWDw",
    alternative_slugs: {
      en: "a-close-up-of-a-blue-object-on-a-white-surface-TQ5unA1BWDw",
      es: "un-primer-plano-de-un-objeto-azul-sobre-una-superficie-blanca-TQ5unA1BWDw",
      ja: "白い表面に青い物体のクローズアップ-TQ5unA1BWDw",
      fr: "un-gros-plan-dun-objet-bleu-sur-une-surface-blanche-TQ5unA1BWDw",
      it: "un-primo-piano-di-un-oggetto-blu-su-una-superficie-bianca-TQ5unA1BWDw",
      ko: "흰색-표면에-파란색-물체가-클로즈업된-모습-TQ5unA1BWDw",
      de: "nahaufnahme-eines-blauen-objekts-auf-weisser-flache-TQ5unA1BWDw",
      pt: "um-close-up-de-um-objeto-azul-em-uma-superficie-branca-TQ5unA1BWDw",
    },
    created_at: "2024-06-09T06:13:09Z",
    updated_at: "2024-07-21T07:40:52Z",
    promoted_at: "2024-07-21T07:40:52Z",
    width: 3840,
    height: 2160,
    color: "#d9d9f3",
    blur_hash: "LUN^#:xubExr~SfhWER.R*oct6ax",
    description: null,
    alt_description: "a close up of a blue object on a white surface",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1717913521927-e42591d63ca0?ixid=M3w2MzUxOTV8MHwxfGFsbHwyfHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1717913521927-e42591d63ca0?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MzUxOTV8MHwxfGFsbHwyfHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1717913521927-e42591d63ca0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzUxOTV8MHwxfGFsbHwyfHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1717913521927-e42591d63ca0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzUxOTV8MHwxfGFsbHwyfHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1717913521927-e42591d63ca0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzUxOTV8MHwxfGFsbHwyfHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1717913521927-e42591d63ca0",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-close-up-of-a-blue-object-on-a-white-surface-TQ5unA1BWDw",
      html: "https://unsplash.com/photos/a-close-up-of-a-blue-object-on-a-white-surface-TQ5unA1BWDw",
      download:
        "https://unsplash.com/photos/TQ5unA1BWDw/download?ixid=M3w2MzUxOTV8MHwxfGFsbHwyfHx8fHx8Mnx8MTcyMTU1NjY5MXw",
      download_location:
        "https://api.unsplash.com/photos/TQ5unA1BWDw/download?ixid=M3w2MzUxOTV8MHwxfGFsbHwyfHx8fHx8Mnx8MTcyMTU1NjY5MXw",
    },
    likes: 11,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "BWQOQJza6Ik",
      updated_at: "2024-07-21T07:40:52Z",
      username: "muriel_1",
      name: "Muriel Liu",
      first_name: "Muriel",
      last_name: "Liu",
      twitter_username: null,
      portfolio_url: "https://weibo.com/2386471593/profile?topnav=1&wvr=6",
      bio: null,
      location: null,
      links: {
        self: "https://api.unsplash.com/users/muriel_1",
        html: "https://unsplash.com/@muriel_1",
        photos: "https://api.unsplash.com/users/muriel_1/photos",
        likes: "https://api.unsplash.com/users/muriel_1/likes",
        portfolio: "https://api.unsplash.com/users/muriel_1/portfolio",
        following: "https://api.unsplash.com/users/muriel_1/following",
        followers: "https://api.unsplash.com/users/muriel_1/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1675262554494-4660354ae80dimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1675262554494-4660354ae80dimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1675262554494-4660354ae80dimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: null,
      total_collections: 0,
      total_likes: 0,
      total_photos: 36,
      total_promoted_photos: 14,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: null,
        portfolio_url: "https://weibo.com/2386471593/profile?topnav=1&wvr=6",
        twitter_username: null,
        paypal_email: null,
      },
    },
  },
  {
    id: "gDN6YjthF7U",
    slug: "a-large-number-of-lanterns-lit-up-at-night-gDN6YjthF7U",
    alternative_slugs: {
      en: "a-large-number-of-lanterns-lit-up-at-night-gDN6YjthF7U",
      es: "un-gran-numero-de-faroles-se-iluminaban-por-la-noche-gDN6YjthF7U",
      ja: "夜になるとライトアップされたたくさんの灯籠-gDN6YjthF7U",
      fr: "un-grand-nombre-de-lanternes-allumees-la-nuit-gDN6YjthF7U",
      it: "un-gran-numero-di-lanterne-illuminate-di-notte-gDN6YjthF7U",
      ko: "밤에는-많은-수의-등불이-켜집니다-gDN6YjthF7U",
      de: "eine-grosse-anzahl-von-laternen-die-nachts-angezundet-wurden-gDN6YjthF7U",
      pt: "um-grande-numero-de-lanternas-acesas-a-noite-gDN6YjthF7U",
    },
    created_at: "2024-07-18T11:13:10Z",
    updated_at: "2024-07-21T07:40:29Z",
    promoted_at: "2024-07-21T07:40:29Z",
    width: 3712,
    height: 5568,
    color: "#f38c0c",
    blur_hash: "L=L-]J}oI?jHNcs-s-S3e;f7oKja",
    description: null,
    alt_description: "A large number of lanterns lit up at night",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1721300374215-d7bc50deb64f?ixid=M3w2MzUxOTV8MHwxfGFsbHwzfHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1721300374215-d7bc50deb64f?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MzUxOTV8MHwxfGFsbHwzfHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1721300374215-d7bc50deb64f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzUxOTV8MHwxfGFsbHwzfHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1721300374215-d7bc50deb64f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzUxOTV8MHwxfGFsbHwzfHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1721300374215-d7bc50deb64f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzUxOTV8MHwxfGFsbHwzfHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1721300374215-d7bc50deb64f",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-large-number-of-lanterns-lit-up-at-night-gDN6YjthF7U",
      html: "https://unsplash.com/photos/a-large-number-of-lanterns-lit-up-at-night-gDN6YjthF7U",
      download:
        "https://unsplash.com/photos/gDN6YjthF7U/download?ixid=M3w2MzUxOTV8MHwxfGFsbHwzfHx8fHx8Mnx8MTcyMTU1NjY5MXw",
      download_location:
        "https://api.unsplash.com/photos/gDN6YjthF7U/download?ixid=M3w2MzUxOTV8MHwxfGFsbHwzfHx8fHx8Mnx8MTcyMTU1NjY5MXw",
    },
    likes: 4,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "LavLtiq4xZo",
      updated_at: "2024-07-21T07:41:54Z",
      username: "novel2199",
      name: "Novel Saleh",
      first_name: "Novel",
      last_name: "Saleh",
      twitter_username: null,
      portfolio_url: null,
      bio: null,
      location: "Indonesia",
      links: {
        self: "https://api.unsplash.com/users/novel2199",
        html: "https://unsplash.com/@novel2199",
        photos: "https://api.unsplash.com/users/novel2199/photos",
        likes: "https://api.unsplash.com/users/novel2199/likes",
        portfolio: "https://api.unsplash.com/users/novel2199/portfolio",
        following: "https://api.unsplash.com/users/novel2199/following",
        followers: "https://api.unsplash.com/users/novel2199/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/placeholder-avatars/extra-large.jpg?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/placeholder-avatars/extra-large.jpg?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/placeholder-avatars/extra-large.jpg?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: null,
      total_collections: 0,
      total_likes: 0,
      total_photos: 24,
      total_promoted_photos: 2,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: null,
        portfolio_url: null,
        twitter_username: null,
        paypal_email: null,
      },
    },
  },
  {
    id: "t_IkF_CNvSY",
    slug: "a-computer-screen-with-a-blue-screen-on-it-t_IkF_CNvSY",
    alternative_slugs: {
      en: "a-computer-screen-with-a-blue-screen-on-it-t_IkF_CNvSY",
      es: "una-pantalla-de-computadora-con-una-pantalla-azul-t_IkF_CNvSY",
      ja: "ブルースクリーンが表示されたコンピューター画面-t_IkF_CNvSY",
      fr: "un-ecran-dordinateur-avec-un-ecran-bleu-dessus-t_IkF_CNvSY",
      it: "schermo-di-un-computer-con-una-schermata-blu-t_IkF_CNvSY",
      ko: "블루-스크린이-있는-컴퓨터-화면-t_IkF_CNvSY",
      de: "ein-computerbildschirm-mit-einem-blauen-bildschirm-t_IkF_CNvSY",
      pt: "uma-tela-de-computador-com-uma-tela-azul-t_IkF_CNvSY",
    },
    created_at: "2024-07-20T11:38:41Z",
    updated_at: "2024-07-21T09:54:16Z",
    promoted_at: "2024-07-21T07:39:51Z",
    width: 3840,
    height: 2160,
    color: "#a6c0c0",
    blur_hash: "LFJRzEWW~Qxa--WYIXob?9odD.NI",
    description:
      "Recently, Microsoft’s Blue Screen of Death made a comeback, proving once again that even in 2024, computers can still throw the ultimate tantrum!",
    alt_description: "A computer screen with a blue screen on it",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1721475246144-98e4f01f3a6c?ixid=M3w2MzUxOTV8MHwxfGFsbHw0fHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1721475246144-98e4f01f3a6c?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MzUxOTV8MHwxfGFsbHw0fHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1721475246144-98e4f01f3a6c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzUxOTV8MHwxfGFsbHw0fHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1721475246144-98e4f01f3a6c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzUxOTV8MHwxfGFsbHw0fHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1721475246144-98e4f01f3a6c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzUxOTV8MHwxfGFsbHw0fHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1721475246144-98e4f01f3a6c",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-computer-screen-with-a-blue-screen-on-it-t_IkF_CNvSY",
      html: "https://unsplash.com/photos/a-computer-screen-with-a-blue-screen-on-it-t_IkF_CNvSY",
      download:
        "https://unsplash.com/photos/t_IkF_CNvSY/download?ixid=M3w2MzUxOTV8MHwxfGFsbHw0fHx8fHx8Mnx8MTcyMTU1NjY5MXw",
      download_location:
        "https://api.unsplash.com/photos/t_IkF_CNvSY/download?ixid=M3w2MzUxOTV8MHwxfGFsbHw0fHx8fHx8Mnx8MTcyMTU1NjY5MXw",
    },
    likes: 9,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      "3d-renders": {
        status: "unevaluated",
      },
      "business-work": {
        status: "unevaluated",
      },
      "current-events": {
        status: "unevaluated",
      },
      "textures-patterns": {
        status: "unevaluated",
      },
      wallpapers: {
        status: "unevaluated",
      },
    },
    asset_type: "photo",
    user: {
      id: "Kg7OSqFJfQE",
      updated_at: "2024-07-21T09:56:58Z",
      username: "fakurian",
      name: "Milad Fakurian",
      first_name: "Milad",
      last_name: "Fakurian",
      twitter_username: "miladfakurian",
      portfolio_url: "https://fakurian.com",
      bio: "Brand designer / Artist",
      location: "Istanbul",
      links: {
        self: "https://api.unsplash.com/users/fakurian",
        html: "https://unsplash.com/@fakurian",
        photos: "https://api.unsplash.com/users/fakurian/photos",
        likes: "https://api.unsplash.com/users/fakurian/likes",
        portfolio: "https://api.unsplash.com/users/fakurian/portfolio",
        following: "https://api.unsplash.com/users/fakurian/following",
        followers: "https://api.unsplash.com/users/fakurian/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1707916347142-c7be5391238fimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1707916347142-c7be5391238fimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1707916347142-c7be5391238fimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "darkniliq",
      total_collections: 0,
      total_likes: 1671,
      total_photos: 734,
      total_promoted_photos: 242,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "darkniliq",
        portfolio_url: "https://fakurian.com",
        twitter_username: "miladfakurian",
        paypal_email: null,
      },
    },
  },
  {
    id: "r_B-PH38vis",
    slug: "a-woman-with-an-umbrella-walking-in-front-of-a-tall-building-r_B-PH38vis",
    alternative_slugs: {
      en: "a-woman-with-an-umbrella-walking-in-front-of-a-tall-building-r_B-PH38vis",
      es: "una-mujer-con-un-paraguas-caminando-frente-a-un-edificio-alto-r_B-PH38vis",
      ja: "高層ビルの前を歩く傘をさした女性-r_B-PH38vis",
      fr: "une-femme-avec-un-parapluie-marchant-devant-un-grand-immeuble-r_B-PH38vis",
      it: "una-donna-con-un-ombrello-che-cammina-davanti-a-un-edificio-alto-r_B-PH38vis",
      ko: "우산을-쓴-여성이-고층-건물-앞을-걷고-있다-r_B-PH38vis",
      de: "eine-frau-mit-einem-regenschirm-geht-vor-einem-hohen-gebaude-r_B-PH38vis",
      pt: "uma-mulher-com-um-guarda-chuva-andando-na-frente-de-um-predio-alto-r_B-PH38vis",
    },
    created_at: "2024-07-15T02:46:15Z",
    updated_at: "2024-07-21T07:38:50Z",
    promoted_at: "2024-07-21T07:38:50Z",
    width: 3904,
    height: 5856,
    color: "#c0c0c0",
    blur_hash: "LLFifE%2-r-V0#juRQxFRRayM_WU",
    description: null,
    alt_description:
      "A woman with an umbrella walking in front of a tall building",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1721011564875-a2c115a8204e?ixid=M3w2MzUxOTV8MHwxfGFsbHw1fHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1721011564875-a2c115a8204e?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MzUxOTV8MHwxfGFsbHw1fHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1721011564875-a2c115a8204e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzUxOTV8MHwxfGFsbHw1fHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1721011564875-a2c115a8204e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzUxOTV8MHwxfGFsbHw1fHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1721011564875-a2c115a8204e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzUxOTV8MHwxfGFsbHw1fHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1721011564875-a2c115a8204e",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-woman-with-an-umbrella-walking-in-front-of-a-tall-building-r_B-PH38vis",
      html: "https://unsplash.com/photos/a-woman-with-an-umbrella-walking-in-front-of-a-tall-building-r_B-PH38vis",
      download:
        "https://unsplash.com/photos/r_B-PH38vis/download?ixid=M3w2MzUxOTV8MHwxfGFsbHw1fHx8fHx8Mnx8MTcyMTU1NjY5MXw",
      download_location:
        "https://api.unsplash.com/photos/r_B-PH38vis/download?ixid=M3w2MzUxOTV8MHwxfGFsbHw1fHx8fHx8Mnx8MTcyMTU1NjY5MXw",
    },
    likes: 4,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      "street-photography": {
        status: "approved",
        approved_on: "2024-07-15T06:55:31Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "zYMbLv23R6Y",
      updated_at: "2024-07-21T07:41:54Z",
      username: "pafuxu",
      name: "Kouji Tsuru",
      first_name: "Kouji",
      last_name: "Tsuru",
      twitter_username: "pafuxu",
      portfolio_url: "https://www.pafuxum.com",
      bio: null,
      location: "Japan",
      links: {
        self: "https://api.unsplash.com/users/pafuxu",
        html: "https://unsplash.com/@pafuxu",
        photos: "https://api.unsplash.com/users/pafuxu/photos",
        likes: "https://api.unsplash.com/users/pafuxu/likes",
        portfolio: "https://api.unsplash.com/users/pafuxu/portfolio",
        following: "https://api.unsplash.com/users/pafuxu/following",
        followers: "https://api.unsplash.com/users/pafuxu/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1518875533804-91b4c3c8ce67?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1518875533804-91b4c3c8ce67?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1518875533804-91b4c3c8ce67?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "pafuxu",
      total_collections: 0,
      total_likes: 1,
      total_photos: 5871,
      total_promoted_photos: 66,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: "pafuxu",
        portfolio_url: "https://www.pafuxum.com",
        twitter_username: "pafuxu",
        paypal_email: null,
      },
    },
  },
  {
    id: "-jXG8UoBJLI",
    slug: "a-person-using-a-laptop-computer-on-a-table--jXG8UoBJLI",
    alternative_slugs: {
      en: "a-person-using-a-laptop-computer-on-a-table--jXG8UoBJLI",
      es: "una-persona-usando-una-computadora-portatil-sobre-una-mesa--jXG8UoBJLI",
      ja: "テーブルの上でノートパソコンを使う人--jXG8UoBJLI",
      fr: "une-personne-utilisant-un-ordinateur-portable-sur-une-table--jXG8UoBJLI",
      it: "una-persona-che-utilizza-un-computer-portatile-su-un-tavolo--jXG8UoBJLI",
      ko: "탁자-위에서-랩톱-컴퓨터를-사용하는-사람--jXG8UoBJLI",
      de: "eine-person-die-einen-laptop-auf-einem-tisch-benutzt--jXG8UoBJLI",
      pt: "uma-pessoa-usando-um-laptop-em-uma-mesa--jXG8UoBJLI",
    },
    created_at: "2024-07-02T16:21:05Z",
    updated_at: "2024-07-21T08:03:51Z",
    promoted_at: null,
    width: 3600,
    height: 2401,
    color: "#d9c0a6",
    blur_hash: "LJK^jC~o~A4o5t%0skNex^nibEIV",
    description: null,
    alt_description: "A person using a laptop computer on a table",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1719937206158-cad5e6775044?ixid=M3w2MzUxOTV8MXwxfGFsbHw2fHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1719937206158-cad5e6775044?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MzUxOTV8MXwxfGFsbHw2fHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1719937206158-cad5e6775044?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzUxOTV8MXwxfGFsbHw2fHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1719937206158-cad5e6775044?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzUxOTV8MXwxfGFsbHw2fHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1719937206158-cad5e6775044?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzUxOTV8MXwxfGFsbHw2fHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1719937206158-cad5e6775044",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-person-using-a-laptop-computer-on-a-table--jXG8UoBJLI",
      html: "https://unsplash.com/photos/a-person-using-a-laptop-computer-on-a-table--jXG8UoBJLI",
      download:
        "https://unsplash.com/photos/-jXG8UoBJLI/download?ixid=M3w2MzUxOTV8MXwxfGFsbHw2fHx8fHx8Mnx8MTcyMTU1NjY5MXw",
      download_location:
        "https://api.unsplash.com/photos/-jXG8UoBJLI/download?ixid=M3w2MzUxOTV8MXwxfGFsbHw2fHx8fHx8Mnx8MTcyMTU1NjY5MXw",
    },
    likes: 2,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: {
      impression_urls: [
        "https://secure.insightexpressai.com/adServer/adServerESI.aspx?script=false&bannerID=12236419&rnd=[timestamp]&redir=https://secure.insightexpressai.com/adserver/1pixel.gif",
      ],
      tagline: "Memory for every endeavor",
      tagline_url: "https://www.samsung.com/us/memory-storage/",
      sponsor: {
        id: "eySMK9KwmJU",
        updated_at: "2024-07-21T08:46:11Z",
        username: "samsungmemory",
        name: "Samsung Memory",
        first_name: "Samsung",
        last_name: "Memory",
        twitter_username: "SamsungSemiUS",
        portfolio_url: "http://www.samsung.com/us/computing/memory-storage/",
        bio: "Memory for every endeavor – get fast storage solutions that work seamlessly with your devices.",
        location: null,
        links: {
          self: "https://api.unsplash.com/users/samsungmemory",
          html: "https://unsplash.com/@samsungmemory",
          photos: "https://api.unsplash.com/users/samsungmemory/photos",
          likes: "https://api.unsplash.com/users/samsungmemory/likes",
          portfolio: "https://api.unsplash.com/users/samsungmemory/portfolio",
          following: "https://api.unsplash.com/users/samsungmemory/following",
          followers: "https://api.unsplash.com/users/samsungmemory/followers",
        },
        profile_image: {
          small:
            "https://images.unsplash.com/profile-1602741027167-c4d707fcfc85image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
          medium:
            "https://images.unsplash.com/profile-1602741027167-c4d707fcfc85image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
          large:
            "https://images.unsplash.com/profile-1602741027167-c4d707fcfc85image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
        },
        instagram_username: "samsungsemiconductor",
        total_collections: 1,
        total_likes: 0,
        total_photos: 880,
        total_promoted_photos: 38,
        total_illustrations: 0,
        total_promoted_illustrations: 0,
        accepted_tos: true,
        for_hire: false,
        social: {
          instagram_username: "samsungsemiconductor",
          portfolio_url: "http://www.samsung.com/us/computing/memory-storage/",
          twitter_username: "SamsungSemiUS",
          paypal_email: null,
        },
      },
    },
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "eySMK9KwmJU",
      updated_at: "2024-07-21T08:46:11Z",
      username: "samsungmemory",
      name: "Samsung Memory",
      first_name: "Samsung",
      last_name: "Memory",
      twitter_username: "SamsungSemiUS",
      portfolio_url: "http://www.samsung.com/us/computing/memory-storage/",
      bio: "Memory for every endeavor – get fast storage solutions that work seamlessly with your devices.",
      location: null,
      links: {
        self: "https://api.unsplash.com/users/samsungmemory",
        html: "https://unsplash.com/@samsungmemory",
        photos: "https://api.unsplash.com/users/samsungmemory/photos",
        likes: "https://api.unsplash.com/users/samsungmemory/likes",
        portfolio: "https://api.unsplash.com/users/samsungmemory/portfolio",
        following: "https://api.unsplash.com/users/samsungmemory/following",
        followers: "https://api.unsplash.com/users/samsungmemory/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1602741027167-c4d707fcfc85image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1602741027167-c4d707fcfc85image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1602741027167-c4d707fcfc85image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "samsungsemiconductor",
      total_collections: 1,
      total_likes: 0,
      total_photos: 880,
      total_promoted_photos: 38,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: "samsungsemiconductor",
        portfolio_url: "http://www.samsung.com/us/computing/memory-storage/",
        twitter_username: "SamsungSemiUS",
        paypal_email: null,
      },
    },
  },
  {
    id: "ephuPQcUEtw",
    slug: "a-night-sky-filled-with-lots-of-stars-ephuPQcUEtw",
    alternative_slugs: {
      en: "a-night-sky-filled-with-lots-of-stars-ephuPQcUEtw",
      es: "un-cielo-nocturno-lleno-de-estrellas-ephuPQcUEtw",
      ja: "たくさんの星がいっぱいの夜空-ephuPQcUEtw",
      fr: "un-ciel-nocturne-rempli-de-nombreuses-etoiles-ephuPQcUEtw",
      it: "un-cielo-notturno-pieno-di-stelle-ephuPQcUEtw",
      ko: "별이-많이-쏟아지는-밤하늘-ephuPQcUEtw",
      de: "ein-nachthimmel-voller-sterne-ephuPQcUEtw",
      pt: "um-ceu-noturno-cheio-de-muitas-estrelas-ephuPQcUEtw",
    },
    created_at: "2024-07-18T09:53:48Z",
    updated_at: "2024-07-21T07:41:36Z",
    promoted_at: "2024-07-21T07:38:22Z",
    width: 4672,
    height: 7008,
    color: "#262626",
    blur_hash: "LD8DR$-ANGNbbvNaays.0yI;s:s.",
    description: null,
    alt_description: "A night sky filled with lots of stars",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1721296382202-8b917fd0963e?ixid=M3w2MzUxOTV8MHwxfGFsbHw3fHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1721296382202-8b917fd0963e?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MzUxOTV8MHwxfGFsbHw3fHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1721296382202-8b917fd0963e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzUxOTV8MHwxfGFsbHw3fHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1721296382202-8b917fd0963e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzUxOTV8MHwxfGFsbHw3fHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1721296382202-8b917fd0963e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzUxOTV8MHwxfGFsbHw3fHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1721296382202-8b917fd0963e",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-night-sky-filled-with-lots-of-stars-ephuPQcUEtw",
      html: "https://unsplash.com/photos/a-night-sky-filled-with-lots-of-stars-ephuPQcUEtw",
      download:
        "https://unsplash.com/photos/ephuPQcUEtw/download?ixid=M3w2MzUxOTV8MHwxfGFsbHw3fHx8fHx8Mnx8MTcyMTU1NjY5MXw",
      download_location:
        "https://api.unsplash.com/photos/ephuPQcUEtw/download?ixid=M3w2MzUxOTV8MHwxfGFsbHw3fHx8fHx8Mnx8MTcyMTU1NjY5MXw",
    },
    likes: 6,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "X20SxD3VV5A",
      updated_at: "2024-07-21T07:38:22Z",
      username: "bylukemiller",
      name: "Luke Miller",
      first_name: "Luke",
      last_name: "Miller",
      twitter_username: "bylukemiller",
      portfolio_url: "https://www.lukemillerphotograph.com",
      bio: "22 year old adventure and travel photographer from British Columbia, Canada.",
      location: "Vancouver British Columbia, Canada",
      links: {
        self: "https://api.unsplash.com/users/bylukemiller",
        html: "https://unsplash.com/@bylukemiller",
        photos: "https://api.unsplash.com/users/bylukemiller/photos",
        likes: "https://api.unsplash.com/users/bylukemiller/likes",
        portfolio: "https://api.unsplash.com/users/bylukemiller/portfolio",
        following: "https://api.unsplash.com/users/bylukemiller/following",
        followers: "https://api.unsplash.com/users/bylukemiller/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1699665121743-ced1edf9daaaimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1699665121743-ced1edf9daaaimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1699665121743-ced1edf9daaaimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "bylukemiller",
      total_collections: 1,
      total_likes: 132,
      total_photos: 846,
      total_promoted_photos: 84,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "bylukemiller",
        portfolio_url: "https://www.lukemillerphotograph.com",
        twitter_username: "bylukemiller",
        paypal_email: null,
      },
    },
  },
  {
    id: "Rj3Mxcwn0io",
    slug: "the-burj-building-in-the-middle-of-the-city-Rj3Mxcwn0io",
    alternative_slugs: {
      en: "the-burj-building-in-the-middle-of-the-city-Rj3Mxcwn0io",
      es: "el-edificio-burj-en-el-centro-de-la-ciudad-Rj3Mxcwn0io",
      ja: "街の真ん中にあるブルジュの建物-Rj3Mxcwn0io",
      fr: "limmeuble-burj-au-milieu-de-la-ville-Rj3Mxcwn0io",
      it: "ledificio-del-burj-nel-centro-della-citta-Rj3Mxcwn0io",
      ko: "도시-한복판에-있는-버즈-빌딩-Rj3Mxcwn0io",
      de: "das-burj-gebaude-mitten-in-der-stadt-Rj3Mxcwn0io",
      pt: "o-edificio-burj-no-meio-da-cidade-Rj3Mxcwn0io",
    },
    created_at: "2024-07-17T16:57:51Z",
    updated_at: "2024-07-21T09:47:11Z",
    promoted_at: "2024-07-21T07:38:01Z",
    width: 4290,
    height: 6435,
    color: "#73a6c0",
    blur_hash: "LaC8n0ofbwbH4Ta}aJj@xCjuofay",
    description: null,
    alt_description: "The burj building in the middle of the city",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1721235421626-a5c5ce155842?ixid=M3w2MzUxOTV8MHwxfGFsbHw4fHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1721235421626-a5c5ce155842?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MzUxOTV8MHwxfGFsbHw4fHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1721235421626-a5c5ce155842?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzUxOTV8MHwxfGFsbHw4fHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1721235421626-a5c5ce155842?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzUxOTV8MHwxfGFsbHw4fHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1721235421626-a5c5ce155842?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzUxOTV8MHwxfGFsbHw4fHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1721235421626-a5c5ce155842",
    },
    links: {
      self: "https://api.unsplash.com/photos/the-burj-building-in-the-middle-of-the-city-Rj3Mxcwn0io",
      html: "https://unsplash.com/photos/the-burj-building-in-the-middle-of-the-city-Rj3Mxcwn0io",
      download:
        "https://unsplash.com/photos/Rj3Mxcwn0io/download?ixid=M3w2MzUxOTV8MHwxfGFsbHw4fHx8fHx8Mnx8MTcyMTU1NjY5MXw",
      download_location:
        "https://api.unsplash.com/photos/Rj3Mxcwn0io/download?ixid=M3w2MzUxOTV8MHwxfGFsbHw4fHx8fHx8Mnx8MTcyMTU1NjY5MXw",
    },
    likes: 7,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "rakmAwMnNLE",
      updated_at: "2024-07-21T07:41:53Z",
      username: "radosky",
      name: "Radek Skrzypczak",
      first_name: "Radek",
      last_name: "Skrzypczak",
      twitter_username: null,
      portfolio_url: "http://phots.pl",
      bio: "amateur photo & video maker 📷 product designer and pixel perfect psychopatch 🚀 games 🎮 movies 🎬 billiards 🎱",
      location: "Poland",
      links: {
        self: "https://api.unsplash.com/users/radosky",
        html: "https://unsplash.com/@radosky",
        photos: "https://api.unsplash.com/users/radosky/photos",
        likes: "https://api.unsplash.com/users/radosky/likes",
        portfolio: "https://api.unsplash.com/users/radosky/portfolio",
        following: "https://api.unsplash.com/users/radosky/following",
        followers: "https://api.unsplash.com/users/radosky/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1721152632538-12b6754ad4c1image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1721152632538-12b6754ad4c1image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1721152632538-12b6754ad4c1image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "radosky_",
      total_collections: 0,
      total_likes: 181,
      total_photos: 28,
      total_promoted_photos: 7,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "radosky_",
        portfolio_url: "http://phots.pl",
        twitter_username: null,
        paypal_email: null,
      },
    },
  },
  {
    id: "HYX-SkM91p0",
    slug: "a-bird-flying-over-a-body-of-water-at-sunset-HYX-SkM91p0",
    alternative_slugs: {
      en: "a-bird-flying-over-a-body-of-water-at-sunset-HYX-SkM91p0",
      es: "un-pajaro-volando-sobre-un-cuerpo-de-agua-al-atardecer-HYX-SkM91p0",
      ja: "夕暮れ時に水面を飛ぶ鳥-HYX-SkM91p0",
      fr: "un-oiseau-survolant-un-plan-deau-au-coucher-du-soleil-HYX-SkM91p0",
      it: "un-uccello-che-sorvola-uno-specchio-dacqua-al-tramonto-HYX-SkM91p0",
      ko: "해질녘-물-위를-날아다니는-새-HYX-SkM91p0",
      de: "ein-vogel-der-bei-sonnenuntergang-uber-ein-gewasser-fliegt-HYX-SkM91p0",
      pt: "um-passaro-voando-sobre-um-corpo-de-agua-ao-por-do-sol-HYX-SkM91p0",
    },
    created_at: "2024-07-14T19:41:21Z",
    updated_at: "2024-07-21T07:37:18Z",
    promoted_at: "2024-07-21T07:37:18Z",
    width: 4423,
    height: 2949,
    color: "#8c400c",
    blur_hash: "LRH9soNI0$odsmf7xZWW$$S2oej@",
    description: null,
    alt_description: "A bird flying over a body of water at sunset",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1720986073399-f5c24e020ca1?ixid=M3w2MzUxOTV8MHwxfGFsbHw5fHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1720986073399-f5c24e020ca1?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MzUxOTV8MHwxfGFsbHw5fHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1720986073399-f5c24e020ca1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzUxOTV8MHwxfGFsbHw5fHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1720986073399-f5c24e020ca1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzUxOTV8MHwxfGFsbHw5fHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1720986073399-f5c24e020ca1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzUxOTV8MHwxfGFsbHw5fHx8fHx8Mnx8MTcyMTU1NjY5MXw&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1720986073399-f5c24e020ca1",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-bird-flying-over-a-body-of-water-at-sunset-HYX-SkM91p0",
      html: "https://unsplash.com/photos/a-bird-flying-over-a-body-of-water-at-sunset-HYX-SkM91p0",
      download:
        "https://unsplash.com/photos/HYX-SkM91p0/download?ixid=M3w2MzUxOTV8MHwxfGFsbHw5fHx8fHx8Mnx8MTcyMTU1NjY5MXw",
      download_location:
        "https://api.unsplash.com/photos/HYX-SkM91p0/download?ixid=M3w2MzUxOTV8MHwxfGFsbHw5fHx8fHx8Mnx8MTcyMTU1NjY5MXw",
    },
    likes: 10,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "37hcgu6t_8I",
      updated_at: "2024-07-21T07:41:53Z",
      username: "2renkov",
      name: "alexey turenkov",
      first_name: "alexey",
      last_name: "turenkov",
      twitter_username: null,
      portfolio_url: "https://www.instagram.com/alexey2renkov/",
      bio: "A photographer from Russia. I shoot everything I see.",
      location: "Russia",
      links: {
        self: "https://api.unsplash.com/users/2renkov",
        html: "https://unsplash.com/@2renkov",
        photos: "https://api.unsplash.com/users/2renkov/photos",
        likes: "https://api.unsplash.com/users/2renkov/likes",
        portfolio: "https://api.unsplash.com/users/2renkov/portfolio",
        following: "https://api.unsplash.com/users/2renkov/following",
        followers: "https://api.unsplash.com/users/2renkov/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1512316832571-8686d3994625?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1512316832571-8686d3994625?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1512316832571-8686d3994625?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "alexey2renkov",
      total_collections: 9,
      total_likes: 92,
      total_photos: 376,
      total_promoted_photos: 38,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: "alexey2renkov",
        portfolio_url: "https://www.instagram.com/alexey2renkov/",
        twitter_username: null,
        paypal_email: null,
      },
    },
  },
  {
    id: "lankt8czhWs",
    slug: "a-large-number-of-lanterns-with-asian-writing-on-them-lankt8czhWs",
    alternative_slugs: {
      en: "a-large-number-of-lanterns-with-asian-writing-on-them-lankt8czhWs",
      es: "un-gran-numero-de-faroles-con-escritura-asiatica-en-ellos-lankt8czhWs",
      ja: "アジアン文字が書かれたランタンがずらりと並んでいます-lankt8czhWs",
      fr: "un-grand-nombre-de-lanternes-avec-des-inscriptions-asiatiques-dessus-lankt8czhWs",
      it: "un-gran-numero-di-lanterne-con-scritte-asiatiche-su-di-esse-lankt8czhWs",
      ko: "아시아식-글씨가-쓰여진-많은-수의-등불-lankt8czhWs",
      de: "eine-grosse-anzahl-von-laternen-mit-asiatischer-schrift-darauf-lankt8czhWs",
      pt: "um-grande-numero-lanternas-com-escrita-asiatica-sobre-eles-lankt8czhWs",
    },
    created_at: "2024-07-18T11:13:10Z",
    updated_at: "2024-07-21T07:35:57Z",
    promoted_at: "2024-07-21T07:35:31Z",
    width: 3712,
    height: 5568,
    color: "#f3a60c",
    blur_hash: "L5OeEb8+HwP3u0Ek904u4tI;thIt",
    description: null,
    alt_description: "A large number of lanterns with asian writing on them",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1721300374809-cd54610c4fe2?ixid=M3w2MzUxOTV8MHwxfGFsbHwxMHx8fHx8fDJ8fDE3MjE1NTY2OTF8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1721300374809-cd54610c4fe2?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MzUxOTV8MHwxfGFsbHwxMHx8fHx8fDJ8fDE3MjE1NTY2OTF8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1721300374809-cd54610c4fe2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzUxOTV8MHwxfGFsbHwxMHx8fHx8fDJ8fDE3MjE1NTY2OTF8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1721300374809-cd54610c4fe2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzUxOTV8MHwxfGFsbHwxMHx8fHx8fDJ8fDE3MjE1NTY2OTF8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1721300374809-cd54610c4fe2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzUxOTV8MHwxfGFsbHwxMHx8fHx8fDJ8fDE3MjE1NTY2OTF8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1721300374809-cd54610c4fe2",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-large-number-of-lanterns-with-asian-writing-on-them-lankt8czhWs",
      html: "https://unsplash.com/photos/a-large-number-of-lanterns-with-asian-writing-on-them-lankt8czhWs",
      download:
        "https://unsplash.com/photos/lankt8czhWs/download?ixid=M3w2MzUxOTV8MHwxfGFsbHwxMHx8fHx8fDJ8fDE3MjE1NTY2OTF8",
      download_location:
        "https://api.unsplash.com/photos/lankt8czhWs/download?ixid=M3w2MzUxOTV8MHwxfGFsbHwxMHx8fHx8fDJ8fDE3MjE1NTY2OTF8",
    },
    likes: 8,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "LavLtiq4xZo",
      updated_at: "2024-07-21T07:41:54Z",
      username: "novel2199",
      name: "Novel Saleh",
      first_name: "Novel",
      last_name: "Saleh",
      twitter_username: null,
      portfolio_url: null,
      bio: null,
      location: "Indonesia",
      links: {
        self: "https://api.unsplash.com/users/novel2199",
        html: "https://unsplash.com/@novel2199",
        photos: "https://api.unsplash.com/users/novel2199/photos",
        likes: "https://api.unsplash.com/users/novel2199/likes",
        portfolio: "https://api.unsplash.com/users/novel2199/portfolio",
        following: "https://api.unsplash.com/users/novel2199/following",
        followers: "https://api.unsplash.com/users/novel2199/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/placeholder-avatars/extra-large.jpg?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/placeholder-avatars/extra-large.jpg?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/placeholder-avatars/extra-large.jpg?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: null,
      total_collections: 0,
      total_likes: 0,
      total_photos: 24,
      total_promoted_photos: 2,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: null,
        portfolio_url: null,
        twitter_username: null,
        paypal_email: null,
      },
    },
  },
];

export const message = {
  errorField: "Please fill empty the field.",
  errorFetch: "Please try again search again...",
};
